spring:
  application:
    name: orders-service

  datasource:
    url: jdbc:postgresql://localhost:5432/orders
    username: admin
    password: admin123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: orders
        format_sql: true
    show-sql: true

  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/orders
    user: admin
    password: admin123
    default-schema: orders
    schemas: orders
    locations: classpath:db/migration

client:
  users:
    url: http://localhost:8082/api/v1/users

server:
  port: 8083